Css four column layout
randygerada/rc1022-code-solutions pull request #52
Opened 2022-10-28 23:26 UTC by randygerada

![Screenshot 2022-10-28 at 4 25 58 PM](https://user-images.githubusercontent.com/113477527/198750147-e02f21bc-dc59-4ea1-9c3b-2d9f7a33d113.png)

2022-10-28 23:40 UTC, Zhiwutian requested changes
Looks good Randy, just needs a small update for the columns

2022-10-28 23:40 UTC, Zhiwutian commented on css-four-column-layout/index.html
> +      <div class="screen-1">
make sure that you are using proper columns here. They need to have a set width / flex basis

2022-10-31 00:52 UTC, randygerada commented
<img width="1726" alt="Screenshot 2022-10-30 at 5 49 44 PM" src="https://user-images.githubusercontent.com/113477527/198910930-05a94ccc-6861-4d8f-b821-5a3efee6db0b.png">

2022-10-31 15:34 UTC, Zhiwutian approved these changes
👍🏼

2022-11-01 16:27 UTC, merged