Completed html forms exercise.
randygerada/rc1022-code-solutions pull request #6
Opened 2022-10-11 21:14 UTC by randygerada

<img width="477" alt="Screen Shot 2022-10-11 at 2 11 53 PM" src="https://user-images.githubusercontent.com/113477527/195199571-7162821e-ee6f-40d3-9479-9c88f62de6c0.png">

2022-10-11 21:20 UTC, Zhiwutian requested changes
Looking good! Just a few small updates

2022-10-11 21:20 UTC, Zhiwutian commented on html-forms/index.html
> +        <input type="text" name="email">
make sure the input has an `id` which matches the `for` attribute on the label

2022-10-11 21:20 UTC, Zhiwutian commented on html-forms/index.html
> +        <select name="choices">
same as above comment

2022-10-11 21:20 UTC, Zhiwutian commented on html-forms/index.html
> +        checked="HTML">
this would need to be attached to the previous line

2022-10-11 21:20 UTC, Zhiwutian commented on html-forms/index.html
> +        <input type="radio" name="language" value="CSS" />
each of these inputs needs their own label

2022-10-11 21:20 UTC, Zhiwutian commented on html-forms/index.html
> +        <input type="checkbox" name="subscribe" value="Sign me up!"/>
make sure to add the proper id here.

2022-10-11 21:20 UTC, Zhiwutian commented on html-forms/index.html
> +        <textarea name="comments" cols="30" rows="10"></textarea>
make sure to add the proper id here

2022-10-12 04:26 UTC, randygerada commented
<img width="613" alt="Screen Shot 2022-10-11 at 9 23 33 PM" src="https://user-images.githubusercontent.com/113477527/195249951-8b366f4f-6269-47fb-8c41-efd1ac554bac.png">

2022-10-12 15:33 UTC, Zhiwutian approved these changes
👍🏼

2022-10-12 15:39 UTC, merged